environment:
  # For Python versions available on Appveyor, see
  # https://www.appveyor.com/docs/windows-images-software/#python
  matrix:
#    - PYTHON: "C:\\Python27"
#    - PYTHON: "C:\\Python33"
#    - PYTHON: "C:\\Python34"
#    - PYTHON: "C:\\Python35"
#    - PYTHON: "C:\\Python36"
#    - PYTHON: "C:\\Python37"
#    - PYTHON: "C:\\Python27-x64"
#    - PYTHON: "C:\\Python33-x64"
#    - PYTHON: "C:\\Python34-x64"
#    - PYTHON: "C:\\Python35-x64"
#    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
      platform: x64
    - PYTHON: "C:\\Python37"
      platform: x86

install:
  - "%PYTHON%\\python.exe -m pip install wheel PyMuPDF pytest pyinstaller"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest"

after_test:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - "%PYTHON%\\python.exe -m PyInstaller --clean --onefile --noconsole plakativ.py"

artifacts:
  - path: dist\*
